<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metamodelHCL" nsURI="http://www.example.org/metamodelHCL" nsPrefix="metamodelHCL">
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Processing" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="processingproperty" lowerBound="5"
        upperBound="5" eType="#//ProcessingProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Storage" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="storageproperty" lowerBound="1"
        eType="#//StorageProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Display" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayproperty" lowerBound="2"
        upperBound="2" eType="#//DisplayProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReusedComponent" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessingProperty" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="SizeTypeEnum">
    <eLiterals name="KiB"/>
    <eLiterals name="MiB" value="1"/>
    <eLiterals name="GiB" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StorageProperty" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DisplayProperty" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Cores" eSuperTypes="#//ProcessingProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Speed" eSuperTypes="#//ProcessingProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cache" abstract="true" eSuperTypes="#//ProcessingProperty"/>
  <eClassifiers xsi:type="ecore:EClass" name="L1" eSuperTypes="#//Cache">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SizeTypeEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="L2" eSuperTypes="#//Cache">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SizeTypeEnum"
        defaultValueLiteral="MiB"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="L3" eSuperTypes="#//Cache">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SizeTypeEnum"
        defaultValueLiteral="MiB"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StorageTypeEnum">
    <eLiterals name="HDD"/>
    <eLiterals name="SSD" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleStorage" eSuperTypes="#//StorageProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stype" lowerBound="1" eType="#//StorageTypeEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssize" lowerBound="1" eType="#//SizeTypeEnum"
        defaultValueLiteral="GiB"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Diagonal" eSuperTypes="#//DisplayProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inch" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="#//DisplayProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dtype" lowerBound="1" eType="#//DisplayTypeEnum"
        defaultValueLiteral="FiveK"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DisplayTypeEnum">
    <eLiterals name="FourK"/>
    <eLiterals name="FiveK" value="1"/>
    <eLiterals name="HD" value="2"/>
    <eLiterals name="FullHD" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Computer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
