site_name: 'AIL Documentation'

nav:
    - Home: 'index.md'
    - AIL:
      - About: 'ail/index.md'
      - 'Concrete Syntax': 'ail/concrete_syntax/index.md'

markdown_extensions:
    - toc:
        permalink: "#"